#gd 129
IT-Siberians/AutenticationMicroservice pull request #1
Opened 2024-08-12 06:23 UTC by NikeTorchwood

2024-08-12 22:23 UTC, m-a-ilnitsky reviewed
О, нашел где писать комментарий))
Написал про то что бросается в глаза, а это в основном элементарные вещи, в основном стиль кода.
Саму доменную логику даже нее пытался анализировать.
Мне кажется лучше поправить стили и вмерджить эти изменения в develop.
Тогда последующие пул-реквесты уже не будут такими огромными

2024-08-12 22:23 UTC, m-a-ilnitsky commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +            return BadRequest("Empty input in required fields");// сделать валидацию ввода
1)  Неправильно возвращать одинаковую ошибку на все случаи.
В этом случае она неинформативна. По ней нельзя понять в чем проблема.
По идее каждой ситуации должна соответствовать своя ошибка
2)  Не уверен, что в таких случаях правильно возвращать 400 BadRequest, т.к. сам синтаксис может быть правильным (если уж дело дошло до 2го и 3го сравнения), просто значения передали неправильные.
Возможно в REST-API так принято, т.к. с REST не работал точно не скажу.
3) В целом, 2я и 3я проверки changeUsernameRequest.Id == Guid.Empty ||         string.IsNullOrWhiteSpace(changeUsernameRequest.Username) на мой взгляд относятся скорее к бизнес логике, а не к контроллеру, хотя на практике тоже иногда делали эти проверки в контроллере, но тогда методы контроллера сильно разрастались

2024-08-12 22:23 UTC, m-a-ilnitsky commented on Application/Repositories.Abstractions/IBaseRepository.cs
> +
Не понял где писать комментарий по всему пул-реквесту в целом.
Поэтому напишу здесь.

Обычно пул-реквест закрывает одну небольшую фичу.
Но в данном случае пул-реквест получается огромным, его действительно трудно как-то осмысленно проверить из-за размера.

В целом, по верхам конечно просмотрел.
Написал про то что бросается в глаза, а это в основном элементарные вещи.
Саму доменную логику даже нее пытался анализировать

2024-08-13 11:03 UTC, Barmalej24 requested changes
Есть несоколько моментов относительно объявления переменных и констант в классах,  сбой в форматировании документации.

2024-08-13 11:03 UTC, Barmalej24 commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        var createUserDto = mapper.Map<CreateUserModel>(creatingUserRequest);
Согласен с Михаилом

2024-08-13 13:29 UTC, m-a-ilnitsky commented on Infrastructure/EntityFramework/UserDbContext.cs
> +}
Согласен с Юрием

2024-08-13 16:17 UTC, oleggolen commented on Application/Services.Contracts/VerifyEmailModel.cs
> +    public string? NewEmail { get; set; }
Почему nullable поле? Новый Email точно не может быть null

2024-08-13 16:18 UTC, oleggolen commented on Application/Services.Implementations/MessageBusPublisher.cs
> +namespace Services.Implementations;
Лишний класс, который не имеет смысла, убрать

2024-08-13 16:19 UTC, oleggolen commented on Domain/Domain.Entities/Guest.cs
> +    public User SignUp() => new(Username, _passwordHash, Email);
Гость может регистрировать пользователя? Это выглядит странно

2024-08-13 16:21 UTC, oleggolen commented on Domain/Domain.ValueObjects/BaseEntities/ValueObject.cs
> +{
Поддерживаю

2024-08-13 16:21 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/Email.cs
> +public class Email : ValueObject<string>
Описание класса тоже надо добавить

2024-08-13 16:21 UTC, oleggolen commented on Domain/Domain.ValueObjects/ValueObjects/PasswordHash.cs
> +public class PasswordHash: ValueObject<string>
Описание класса добавить

2024-08-13 16:23 UTC, oleggolen commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        byte[] hash = KeyDerivation.Pbkdf2(password, salt, KeyDerivationPrf.HMACSHA512, Iterations, KeySize);
Что это вообще такое?

2024-08-13 16:25 UTC, oleggolen commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        return $"{Convert.ToBase64String(salt)}.{Convert.ToBase64String(hash)}";
Base64 безопасно, безопаснее использовать алгоримтмы хеширования SHA HMAC 256 или 512 или алгоритмы симметричного шифрования, например, AES256

2024-08-13 16:27 UTC, oleggolen commented on Infrastructure/Repositories.Implementations/InMemoryRepository/BaseInMemoryRepository.cs
> +        var entityToUpdate = await GetByIdAsync(id) ?? throw new ArgumentNullException(nameof(id));
Почему бросание исключение, а не более мягкий возврат значения, например bool?

2024-08-13 16:28 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpGet]
Согласен

2024-08-13 16:28 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [Route("GetUser/{id}", Name = "GetUserById")]
Что это?

2024-08-13 16:29 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        if (id == Guid.Empty)
Добавить FluentValidation или Model Validation и перенести проверку, также можно использовать ограничение на параметр в аттрибуте перед action методом

2024-08-13 16:30 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        if (user == null) //объясните
Что здесь объяснить?

2024-08-13 16:31 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        var createUserDto = mapper.Map<CreateUserModel>(creatingUserRequest);
Согласен

2024-08-13 16:32 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +            changeUsernameRequest.Id == Guid.Empty ||
Для валидации полей лучше использовать FluentValidation или Model Validation attributes

2024-08-13 16:33 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +            return Ok($"A request has been created to change the email address to {changeEmailDto.NewEmail}. Check your email for confirmation.");
Лучше возвращать более осмысленный ответ в результате этого метода, например, новый Elmail, либо не возвращать ничего, используя возврат кода 204 NoContent

2024-08-13 16:34 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        return NotFound(deleteResult);
Во-первых, при успешном выполнении метода удаления лучше всего возвращать статус когд 204 NoContent, а на существование такого пользователя лучше добавить дополнительную проверку и возвращать 404 с конкретным результатом, например Id пользователя

2024-08-13 16:36 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/ChangePasswordRequest.cs
> +    public string? Password { get; set; }
Зачем здесь nullable поля?

2024-08-13 16:36 UTC, oleggolen commented on WebApi/WebApiAuthenticate/Models/ChangePasswordRequest.cs
> +    public string? NewPassword { get; set; }
Зачем здесь nullable поля?

2024-08-13 16:40 UTC, oleggolen requested changes
В целом хороший код, сделано очень много: репозитории, контроллеры, работа с EF, слои бизнес логики.
По стилю и написанию кода следует изменить:
1. Убрать nullable поля там, где они не нужны
2. Возвращать более корректные статус коды для более простой обработке на фронте
3. Добавить аттрибуты к методам, показывающие получаемые статус коды из метода
4. Убрать лишние комментарии
5. Добавить комментарии к классам моделей, где их нет
6. Прокомментировать неочевидные строки с шифрованием и убрать лишлние алгоритмы из методов ширования
Очень надеюсь, что получится исправить указанные замечания, и тогда получится хорошо работающий более понятный и очевидный код с очень хорошей документацией

2024-08-14 04:12 UTC, closed without merging

2024-08-17 14:19 UTC, NikeTorchwood commented on Application/Services.Abstractions/IMessageBusPublisher.cs
> +public interface IMessageBusPublisher
удалил

2024-08-17 14:25 UTC, NikeTorchwood commented on Application/Services.Contracts/VerifyEmailModel.cs
> +    public string? NewEmail { get; set; }
убрал nullable поля везде

2024-08-17 14:26 UTC, NikeTorchwood commented on Application/Services.Implementations/Mapping/UserMappingsProfile.cs
> +            //Username mapping
исправлено

2024-08-17 14:26 UTC, NikeTorchwood commented on Application/Services.Implementations/MessageBusPublisher.cs
> +namespace Services.Implementations;
исправлено

2024-08-17 14:50 UTC, NikeTorchwood commented on Application/Services.Implementations/MessageBusPublisher.cs
> +public class MessageBusPublisher : IMessageBusPublisher
исправлено, где увидел

2024-08-17 14:59 UTC, NikeTorchwood commented on Domain/Domain.Entities/Guest.cs
> +    public User SignUp() => new(Username, _passwordHash, Email);
создание пользователя результат регистрации гостя

2024-08-17 15:01 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/BaseEntities/ValueObject.cs
> +{
исправлено

2024-08-17 15:01 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/BaseEntities/ValueObject.cs
> +    /// <summary>
исправлено

2024-08-17 15:03 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/Email.cs
> +public class Email : ValueObject<string>
исправлено

2024-08-17 15:08 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/Email.cs
> +    /// <summary>
исправлено

2024-08-17 15:11 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/Email.cs
> +            throw new ArgumentNullException(nameof(value), "Email cannot null or empty");
планируется замена на кастомные эксепшн, не исправлено

2024-08-17 15:12 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/PasswordHash.cs
> +public class PasswordHash: ValueObject<string>
исправлено

2024-08-17 15:13 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/PasswordHash.cs
> +    /// <summary>
исправлено

2024-08-17 15:13 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/PasswordHash.cs
> +    public const int MaxPasswordHashLength = 256;//TODO:выделить в отдельные статические файлы
исправлено

2024-08-17 15:15 UTC, NikeTorchwood commented on Domain/Domain.ValueObjects/ValueObjects/PasswordHash.cs
> +            throw new ArgumentNullException(nameof(value), "PasswordHash cannot null or empty");//TODO:кастомные Exception
исправлено

2024-08-17 15:19 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [HttpGet]
исправлено

2024-08-17 15:20 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Models/ChangePasswordRequest.cs
> +    public string? Password { get; set; }
исправлено

2024-08-17 15:35 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Program.cs
> +    public static void Main(string[] args)
исправлено

2024-08-17 15:39 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Models/ChangePasswordRequest.cs
> +    public string? NewPassword { get; set; }
исправлено

2024-08-17 19:16 UTC, NikeTorchwood commented on Infrastructure/Repositories.Implementations/InMemoryRepository/BaseInMemoryRepository.cs
> +        var entityToUpdate = await GetByIdAsync(id) ?? throw new ArgumentNullException(nameof(id));
исправлено

2024-08-17 20:31 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        return NotFound(deleteResult);
исправлено

2024-08-17 21:10 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +            return Ok($"A request has been created to change the email address to {changeEmailDto.NewEmail}. Check your email for confirmation.");
не понял, там же есть указание на новый эмейл, лучше вообще убрать "ручную запись"?

2024-08-18 07:31 UTC, NikeTorchwood commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        byte[] hash = KeyDerivation.Pbkdf2(password, salt, KeyDerivationPrf.HMACSHA512, Iterations, KeySize);
исправлено

2024-08-18 07:31 UTC, NikeTorchwood commented on Infrastructure/PasswordHasher/CustomPasswordHasher.cs
> +        return $"{Convert.ToBase64String(salt)}.{Convert.ToBase64String(hash)}";
исправлено

2024-08-18 07:32 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +    [Route("GetUser/{id}", Name = "GetUserById")]
а что не так?))))

2024-08-18 07:32 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        if (user == null) //объясните
исправлено

2024-08-18 11:04 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +            changeUsernameRequest.Id == Guid.Empty ||
исправлено

2024-08-18 11:04 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        var createUserDto = mapper.Map<CreateUserModel>(creatingUserRequest);
исправлено

2024-08-18 11:05 UTC, NikeTorchwood commented on WebApi/WebApiAuthenticate/Controllers/UsersController.cs
> +        if (id == Guid.Empty)
исправлено